### PR TITLE
Property Widget: Render header when too many element selected

### PR DESCRIPTION
**Pull request by saskliutas**
Closes https://github.com/iTwin/viewer-components-react/issues/592

### CODE REVIEW

**Review by grigasp — COMMENTED** [review]
Is there an advantage of moving rendering of `FilteringPropertyGrid` up to `PropertyGrid` component over the following approaches?
- Pass `isOverLimit` flag to `PropertyGridContent` and render the message there.
- Render the outer `div` and header in `PropertyGrid`. This would also allow us avoid the addition to our public API.

**Comment by saskliutas** [comment]
> Is there an advantage of moving rendering of `FilteringPropertyGrid` up to `PropertyGrid` component over the following approaches?
> 
> * Pass `isOverLimit` flag to `PropertyGridContent` and render the message there.
> * Render the outer `div` and header in `PropertyGrid`. This would also allow us avoid the addition to our public API.

* `PropertyGridContent` is resused between `PropertyGrid` that is hooked into unified selection and `SingleElementPropertyGrid` so introducing `isOverLimit` and rendering `Too many element` message does not make sense for `SingleEmelementPropertyGrid` use case.
* Rendering div and header in `PropertyGrid` means that we need to duplicate same code in `SingleElementPropertyGrid`

I don't see an issue introducing `dataRenderer` property on `PropertyGridContentProps` interface. This interface is public only because parts of it are used to define `PropertyGridProps` and `SingleElementPropertyGridProps` interface. `PropertyGridContent` is `internal` component and the new `dataRenderer` prop is not exposed through `PropertyGridProps` or `SingleElementPropertyGridProps`.

**Comment by grigasp** [comment]
Thanks, that makes sense.

> I don't see an issue introducing `dataRenderer` property on `PropertyGridContentProps` interface. This interface is public only because parts of it are used to define `PropertyGridProps` and `SingleElementPropertyGridProps` interface. `PropertyGridContent` is internal component and the new `dataRenderer` prop is not exposed through `PropertyGridProps` or `SingleElementPropertyGridProps`.

Should the property be marked `@internal` then?

**Comment by saskliutas** [comment]
> Thanks, that makes sense.
> 
> > I don't see an issue introducing `dataRenderer` property on `PropertyGridContentProps` interface. This interface is public only because parts of it are used to define `PropertyGridProps` and `SingleElementPropertyGridProps` interface. `PropertyGridContent` is internal component and the new `dataRenderer` prop is not exposed through `PropertyGridProps` or `SingleElementPropertyGridProps`.
> 
> Should the property be marked `@internal` then?

Yes, I was thinking about it. Probably all properties from `PropertyGridContentProps` that are omitted on `PropertyGridProps` should be marked `internal`. I will add that.

**Review by grigasp — APPROVED** [review]

**Pull request merged**
