### PR TITLE
Refactored SubLayers tree panel and made it independent from viewport

### PR DESCRIPTION
**Pull request by mdastous-bentley**

### CODE REVIEW

**Comment by mdastous-bentley** [comment]
@eringram please review

**Review by eringram — APPROVED** [review]

**Comment by mdastous-bentley** [comment]
@aruniverse review needed on this one too

**Review by aruniverse — APPROVED** [review]
why did this need my approval after getting erins?

**Comment by aruniverse** [comment]
i think the pipeline just needs to be re-triggered. maybe push a dummy commit

**Pull request merged**
