### PR TITLE
Added @itwin\map-layers-formats to peerDependencies

### PR DESCRIPTION
**Pull request by mdastous-bentley**

### CODE REVIEW

**Comment by mdastous-bentley** [comment]
@aruniverse As requested.

**Review by aruniverse — CHANGES_REQUESTED** [review]
lockfile changes?

**Comment by mdastous-bentley** [comment]
@aruniverse I looked into it and coulndnt find anything.  Maybe it didn't get updated because it was already a devDep ? @ben-polinsky

**Review by aruniverse — APPROVED** [review]
This is technically breaking but I don't see how this worked without this before so

**Review by eringram — APPROVED** [review]

**Pull request merged**
