### PR TITLE
Feature/property grid null value persistence

### PR DESCRIPTION
**Pull request by usjpin**
PR to add persistence to the toggle null value context menu item feature.

### CODE REVIEW

**Comment by calebmshafer** [comment]
@diegopinate @JoeZman do you guys mind taking a look at the property grid changes?

**Comment by aruniverse** [comment]
> @diegopinate @JoeZman do you guys mind taking a look at the property grid changes?

This is for Justin and the DR team. Ill ping him again about this.

**Comment by calebmshafer** [comment]
@aruniverse any luck when checking in with the teams? If not, is this still valid in the 3.0 version of this package?

**Comment by aruniverse** [comment]
> @aruniverse any luck when checking in with the teams? If not, is this still valid in the 3.0 version of this package?

Last I heard over a month ago, they were going to pick this up again. This uses shared settings so not applicable to 3.0. Im closing this pr, and if they want to add this, we can reopen it.

cc @jjbeckman13 @jason-crow

**Pull request closed without merging**
